# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=200)),
                ('to_name', models.CharField(max_length=200)),
                ('sender', models.CharField(db_column='from', max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
            ],
        ),
    ]
